Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: my-nd-key
      ImageId: "ami-09e67e426f25ce0d7" # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t3.micro
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: PublicIp
      Type: String
      Value: !Join ["", ["http://", !GetAtt EC2Instance.PublicIp, ":3000"]]      

Outputs:
  PublicIp:
    Description: Server Public IP
    Value: !Join ["", ["http://", !GetAtt EC2Instance.PublicIp, ":3000"]]
    Export:
      Name: !Sub "PublicIp"    

